Traceback (most recent call last):
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\main_formal.py", line 153, in <module>
    trainer.train_all()
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\trainer.py", line 104, in train_all
    model.train(**train_args, model_save_path=save_path)
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 581, in train
    self._test()
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 769, in _test
    ) = self._outputs_losses(
        ^^^^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 491, in _outputs_losses
    outs = outputs_losses(inputs, targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 282, in outputs_losses_train
    return outputs_losses(True, inputs, targets, self.data.losses_train)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 270, in outputs_losses
    losses = losses_fn(targets, outputs_, loss_fn, inputs, self, self.net.auxiliary_vars)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\data\data.py", line 13, in losses_train
    return self.losses(targets, outputs, loss_fn, inputs, model, aux=aux)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\data\pde.py", line 127, in losses
    f = self.pde(inputs, outputs_pde)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\src\pde\swe.py", line 238, in swe_2d_var_rain
    rain=self.rain_func(x)          #rainfall intensity,cm/min
         ^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable
