Traceback (most recent call last):
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\main_formal.py", line 148, in <module>
    trainer.train_all()
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\trainer.py", line 104, in train_all
    model.train(**train_args, model_save_path=save_path)
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 581, in train
    self._test()
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 769, in _test
    ) = self._outputs_losses(
        ^^^^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 491, in _outputs_losses
    outs = outputs_losses(inputs, targets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 282, in outputs_losses_train
    return outputs_losses(True, inputs, targets, self.data.losses_train)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\papers\PINN\PINN_SWE-mywork\PINN_SWE-mywork\deepxde\model.py", line 276, in outputs_losses
    losses *= torch.as_tensor(loss_weights)
RuntimeError: The size of tensor a (21) must match the size of tensor b (25) at non-singleton dimension 0
